
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import SecretSantaContractArtifactJson from '../target/secret_santa_contract-SecretSanta.json' with { type: 'json' };
export const SecretSantaContractArtifact = loadContractArtifact(SecretSantaContractArtifactJson as NoirCompiledContract);


      export type SlotClaimed = {
        game_id: FieldLike
slot: FieldLike
      }
    

      export type ReceiverClaimed = {
        game_id: FieldLike
slot: FieldLike
      }
    

/**
 * Type-safe interface for contract SecretSanta;
 */
export class SecretSantaContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, SecretSantaContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): SecretSantaContract {
    return Contract.at(address, SecretSantaContract.artifact, wallet) as SecretSantaContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<SecretSantaContract>(PublicKeys.default(), wallet, SecretSantaContractArtifact, (instance, wallet) => SecretSantaContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<SecretSantaContract>(publicKeys, wallet, SecretSantaContractArtifact, (instance, wallet) => SecretSantaContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof SecretSantaContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<SecretSantaContract['methods'][M]>
  ) {
    return new DeployMethod<SecretSantaContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      SecretSantaContractArtifact,
      (instance, wallet) => SecretSantaContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return SecretSantaContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(SecretSantaContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'next_game_id' | 'game_phases' | 'participant_counts' | 'max_participants' | 'slot_claimed' | 'slot_encryption_keys' | 'slot_delivery_data' | 'participants' | 'sender_assignments' | 'receiver_claims' | 'slot_receiver_claimed' | 'receiver_claim_counts' | 'sender_registration_counts'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
next_game_id: {
      slot: new Fr(3n),
    },
game_phases: {
      slot: new Fr(4n),
    },
participant_counts: {
      slot: new Fr(5n),
    },
max_participants: {
      slot: new Fr(6n),
    },
slot_claimed: {
      slot: new Fr(7n),
    },
slot_encryption_keys: {
      slot: new Fr(8n),
    },
slot_delivery_data: {
      slot: new Fr(9n),
    },
participants: {
      slot: new Fr(10n),
    },
sender_assignments: {
      slot: new Fr(11n),
    },
receiver_claims: {
      slot: new Fr(12n),
    },
slot_receiver_claimed: {
      slot: new Fr(13n),
    },
receiver_claim_counts: {
      slot: new Fr(14n),
    },
sender_registration_counts: {
      slot: new Fr(15n),
    }
      } as ContractStorageLayout<'admin' | 'next_game_id' | 'game_phases' | 'participant_counts' | 'max_participants' | 'slot_claimed' | 'slot_encryption_keys' | 'slot_delivery_data' | 'participants' | 'sender_assignments' | 'receiver_claims' | 'slot_receiver_claimed' | 'receiver_claim_counts' | 'sender_registration_counts'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** advance_phase(game_id: field) */
    advance_phase: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** claim_as_receiver(game_id: field, target_slot: integer, encrypted_delivery_data: array) */
    claim_as_receiver: ((game_id: FieldLike, target_slot: (bigint | number), encrypted_delivery_data: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_game(min_participants: integer, max_participants_param: integer) */
    create_game: ((min_participants: (bigint | number), max_participants_param: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** enroll(game_id: field) */
    enroll: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_all_claimed_slots(game_id: field, max_slots: integer) */
    get_all_claimed_slots: ((game_id: FieldLike, max_slots: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_all_receiver_claimed_slots(game_id: field, max_slots: integer) */
    get_all_receiver_claimed_slots: ((game_id: FieldLike, max_slots: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_game_phase(game_id: field) */
    get_game_phase: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_game_state(game_id: field) */
    get_game_state: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_max_participants(game_id: field) */
    get_max_participants: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_next_game_id() */
    get_next_game_id: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_participant_count(game_id: field) */
    get_participant_count: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_receiver_claim_count(game_id: field) */
    get_receiver_claim_count: ((game_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_slot_delivery_data(game_id: field, slot: field) */
    get_slot_delivery_data: ((game_id: FieldLike, slot: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_slot_encryption_key(game_id: field, slot: field) */
    get_slot_encryption_key: ((game_id: FieldLike, slot: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_slot_claimed(game_id: field, slot: field) */
    is_slot_claimed: ((game_id: FieldLike, slot: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_slot_receiver_claimed(game_id: field, slot: field) */
    is_slot_receiver_claimed: ((game_id: FieldLike, slot: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_as_sender(game_id: field, chosen_slot: integer, encryption_key: struct) */
    register_as_sender: ((game_id: FieldLike, chosen_slot: (bigint | number), encryption_key: { x: FieldLike, y: FieldLike, is_infinite: boolean }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { SlotClaimed: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, ReceiverClaimed: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      SlotClaimed: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "game_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "slot",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "SecretSanta::SlotClaimed"
},
        eventSelector: EventSelector.fromString("0x49b1ba48"),
        fieldNames: ["game_id","slot"],
      },
ReceiverClaimed: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "game_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "slot",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "SecretSanta::ReceiverClaimed"
},
        eventSelector: EventSelector.fromString("0x0d877898"),
        fieldNames: ["game_id","slot"],
      }
    };
  }
  
}
